# Development env get ENV variables from .env config file.
# Production and staging get ENV variables from Heroku or Codeship.
# Test need to use `export` in deploy setup or sample vaiables from this file.

---
default: &default
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  secret_key_base: e8807d40e7727117d016eccf46bb6816479c4d99219a83bffb854eb74d791236fede568deca5ea66a603187a8c0d063ca6be3dfa010d7b02db7eda84920a42e5
